"""add subcategories and relationship

Revision ID: aa630f27f9b0
Revises: 66bc96d051b3
Create Date: 2025-01-05 02:06:23.918247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa630f27f9b0"
down_revision: Union[str, None] = "66bc96d051b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subcategories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name="fk_subcategories_category_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "items", sa.Column("subcategory_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_items_subcategory_id",
        "items",
        "subcategories",
        ["subcategory_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_items_subcategory_id", "items", type_="foreignkey")
    op.drop_column("items", "subcategory_id")
    op.drop_table("subcategories")
    # ### end Alembic commands ###
