"""update item model - add categories and subcategories

Revision ID: 7b287efb244b
Revises: 48a9ec3ecb87
Create Date: 2025-01-02 17:00:28.037807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b287efb244b'
down_revision: Union[str, None] = '48a9ec3ecb87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('items', sa.Column('subcategory_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'items', 'subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'subcategory_id')
    op.drop_column('items', 'category_id')
    op.drop_table('subcategories')
    op.drop_table('categories')
    # ### end Alembic commands ###
